### ISSUE TITLE
libcrypto.so.1.0.0 missing

### ISSUE THREAD

**Issue by jonashrem** [lsellens/service.downloadmanager.transmission#1]
after the latest transmission update right now, transmission was unable to start on libreelec 7.95.1 due to missing **libcrypto.so.1.0.0.**

System is rp2
> 
> LibreELEC:~/.kodi/addons/service.downloadmanager.transmission # ldd bin/transmission-daemon 
>         linux-vdso.so.1 (0x7eb8a000)
>         /usr/lib/libarmmem.so (0x76f1f000)
>         libcurl.so.4 => /usr/lib/libcurl.so.4 (0x76eb8000)
>         librt.so.1 => /usr/lib/librt.so.1 (0x76ea1000)
>         libcrypto.so.1.0.0 => not found
>         libz.so.1 => /usr/lib/libz.so.1 (0x76e8e000)
>         libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76e62000)
>         libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76e3a000)
>         libc.so.6 => /usr/lib/libc.so.6 (0x76d03000)
>         libssl.so.39 => /usr/lib/libssl.so.39 (0x76cc1000)
>         libcrypto.so.38 => /usr/lib/libcrypto.so.38 (0x76b72000)
>         libm.so.6 => /usr/lib/libm.so.6 (0x76af4000)
>         /lib/ld-linux-armhf.so.3 (0x76f34000)
>         libresolv.so.2 => /usr/lib/libresolv.so.2 (0x76ad0000)
> 

After I manually copied it to lib order, I was able to start transmission

**Comment by lsellens** [comment]
Weird it should be looking for libcrypto.so.38 I'll put up an update in just a bit. Have to run out for a while.

**Comment by jonashrem** [comment]
it seems to be linked against libcrypto.so.38  as well (look at the ldd output)

>  libcrypto.so.1.0.0 => not found
> ...
>  libcrypto.so.38 => /usr/lib/libcrypto.so.38 (0x76b72000)

**Comment by lsellens** [comment]
7.95.2 is up now. Should work. Please reopen if it doesn't. Thanks for the bug report!
